// <auto-generated />
namespace BudgetManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Meh : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Meh));
        
        string IMigrationMetadata.Id
        {
            get { return "202001192159488_Meh"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
